int
insert_items(const char *save_path, int amount, char name[16]);

char items[255][16] = {
   "Master Ball",
   "Ultra Ball",
   "Great Ball",
   "Poké Ball",
   "Town Map",
   "Bicycle",
   "?????",
   "Safari Ball",
   "Pokédex",
   "Moon Stone",
   "Antidote",
   "Burn Heal",
   "Ice Heal",
   "Awakening",
   "Parlyz Heal",
   "Full Restore",
   "Max Potion",
   "Hyper Potion",
   "Super Potion",
   "Potion",
   "BoulderBadge",
   "CascadeBadge",
   "ThunderBadge",
   "RainbowBadge",
   "SoulBadge",
   "MarshBadge",
   "VolcanoBadge",
   "EarthBadge",
   "Escape Rope",
   "Repel",
   "Old Amber",
   "Fire Stone",
   "Thunderstone",
   "Water Stone",
   "HP Up",
   "Protein",
   "Iron",
   "Carbos",
   "Calcium",
   "Rare Candy",
   "Dome Fossil",
   "Secret Key",
   "?????",
   "Bike Voucher",
   "X Accuracy",
   "Leaf Stone",
   "Card Key",
   "Nugget",
   "PP UP",
   "Poké Doll",
   "Full Heal",
   "Revive",
   "Max Revive",
   //TODO: review the usage of this dot
   "Guard Spec.", 
   "Super Repel",
   "Max Repel",
   "Dire Hit",
   "Coin",
   "Fresh Water",
   "Soda Pop",
   "Lemonade",
   "S. S. Ticket",
   "Gold Teeth",
   "X Attack",
   "X Defend",
   "X Special",
   "Coin Case",
   "Oak's Parcel",
   "Itemfinder",
   "Silph Scope",
   "Poké Flute",
   "Lift Key",
   "Exp. All",
   "Old Rod",
   "Good Rod",
   "Super Rod",
   "PP Up",
   "Ether",
   "Max Ether",
   "Elixer",
   "Max Elixer",
   "HM01",
   "HM02",
   "HM03",
   "HM04",
   "HM05",
   "TM1",
   "TM2",
   "TM3",
   "TM4",
   "TM5",
   "TM6",
   "TM7",
   "TM8",
   "TM9",
   "TM10",
   "TM11",
   "TM12",
   "TM13",
   "TM14",
   "TM15",
   "TM16",
   "TM17",
   "TM18",
   "TM19",
   "TM20",
   "TM21",
   "TM22",
   "TM23",
   "TM24",
   "TM25",
   "TM26",
   "TM27",
   "TM28",
   "TM29",
   "TM30",
   "TM31",
   "TM32",
   "TM33",
   "TM34",
   "TM35",
   "TM36",
   "TM37",
   "TM38",
   "TM39",
   "TM40",
   "TM41",
   "TM42",
   "TM43",
   "TM44",
   "TM45",
   "TM46",
   "TM47",
   "TM48",
   "TM49",
   "TM50",
   "TM51",
   "TM52",
   "TM53",
   "TM54",
   "TM55"
};
